version: '3.4'

services:
  pgadmiss:
    image: pgadmiss
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8088:8088
  zookeeper:
    image: bitnami/zookeeper
    ports:
      - 2181:2181
  kafka:
    image: bitnami/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVANCED_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOO_KEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
