server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pgadmin?characterEncoding=utf8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 12345678
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations:
        - classpath:static/
        - classpath:templates/
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
  kafka:
    bootstrap-servers: 127.0.0.1:9092
springdoc:
  swagger-ui:
    path: /test
  api-docs:
    path: /api-docs
    enabled: true
logging:
  level:
    org.hibernate.type.descriptor.sql: trace 
mybatis:
    mapper-locations: classpath:mapper/*.xml

# object:
#     storage:
#         path: /Users/admin/Project/VSCode/document/pdadmiss